name: Sync labels
on:
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest

    steps:
      - uses: EndBug/label-sync@v2
        with:
          source-repo: paquetromania/paquet

          delete-other-labels: true

          dry-run: true

          token: ${{ secrets.GITHUB_TOKEN }}